/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Practicas;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author alumno
 */
public class Togglebuittons extends javax.swing.JFrame {

    /**
     * Creates new form Togglebuittons
     */
    public Togglebuittons() {
        initComponents();
        this.setTitle("TOGGLE");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
         Image icono = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/img/icono.png"));
       this.setIconImage(icono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPrecioBase = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        etiTotal = new javax.swing.JLabel();
        tbtnInstalacion = new javax.swing.JToggleButton();
        tbtnFormacion = new javax.swing.JToggleButton();
        tbtnAlimentacionBD = new javax.swing.JToggleButton();
        etiPrecioInstalacion = new javax.swing.JLabel();
        etiPrecioFormacion = new javax.swing.JLabel();
        etiPrecioAlimentacionBD = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Precio base");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 90, -1));
        getContentPane().add(txtPrecioBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 150, 30));

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        etiTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(etiTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 110, 40));

        tbtnInstalacion.setText("Instalacion");
        getContentPane().add(tbtnInstalacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        tbtnFormacion.setText("Formacion");
        getContentPane().add(tbtnFormacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        tbtnAlimentacionBD.setText("Alimentacion BD");
        getContentPane().add(tbtnAlimentacionBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        etiPrecioInstalacion.setText("40");
        getContentPane().add(etiPrecioInstalacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 50, 30));

        etiPrecioFormacion.setText("200");
        getContentPane().add(etiPrecioFormacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 70, 20));

        etiPrecioAlimentacionBD.setText("200");
        getContentPane().add(etiPrecioAlimentacionBD, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
   double precio_base;
double precio_instal; 
double precio_for;
double precio_ali; 
precio_base = Double.parseDouble(txtPrecioBase.getText());
precio_instal = Double.parseDouble(etiPrecioInstalacion.getText());
precio_for = Double.parseDouble(etiPrecioFormacion.getText());
precio_ali = Double.parseDouble(etiPrecioAlimentacionBD.getText());

double precio_total;
precio_total = precio_base;
if (tbtnInstalacion.isSelected()) { 
precio_total = precio_total+precio_instal;
}
if (tbtnFormacion.isSelected()) { 
precio_total = precio_total+precio_for;
}
if (tbtnAlimentacionBD.isSelected()) { 
precio_total = precio_total+precio_ali;
}

etiTotal.setText(precio_total+" €");
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Togglebuittons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Togglebuittons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Togglebuittons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Togglebuittons.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Togglebuittons().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JLabel etiPrecioAlimentacionBD;
    private javax.swing.JLabel etiPrecioFormacion;
    private javax.swing.JLabel etiPrecioInstalacion;
    private javax.swing.JLabel etiTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton tbtnAlimentacionBD;
    private javax.swing.JToggleButton tbtnFormacion;
    private javax.swing.JToggleButton tbtnInstalacion;
    private javax.swing.JTextField txtPrecioBase;
    // End of variables declaration//GEN-END:variables
}
